// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package database

import (
	"database/sql"
	"time"
)

type Req struct {
	ID           int64
	SsID         int64
	Source       string
	ResponseTime int32
	IsSuccessful bool
}

type Ss struct {
	ID            int64
	SubID         int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	Sslink        string
	Ip            string
	Port          int32
	Secret        string
	Name          string
	ApiReportedIp sql.NullString
}

type Sub struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Url       string
}
